   #-------------------------------- DOMAINS -------------------------------

bandomain: https://www.hyblixel.net/appeal
mutedomain: https://www.hybixel.net/mutes
kickdomain: https://www.hybixel.net/kick
serverdomain: mc.hyblixel.net
storedomain: https://www.hyblixel.net/store

servername: Hyblixel

   #-------------------------------- LINKS -------------------------------
youtubelink: https://youtube.com/@HyblixelNetwork