name: SkyblockGame
author: Zero2Sixty2 
main: me.zero.skyblock.main.SkyblockGame
version: 2.0
api-version: 1.12.2
commands:
  fly:
  kaboom:
  debug:
  ping:
  announce:
  boop:
  gm: 
  mute:
  unmute:
  kick:
  tempban:
  ban:
  unban:
  op:
  reboot:
  maintenance:
  bypass:
  help:
  replacehubportal:
  noportal:
  reloadSkyblockGame:
  godmode:
  setrank:
  coins:
  setrank:
  skyblockxp:
  test: